config/routes.rb
Rails.application.routes.draw do

  resources :players

  resources :teams do
    resources :assignments
  end

  resources :assignments

   get '/leader' => 'players#leaders'

  root 'sessions#welcome'

  # home_path
   get '/home' => 'sessions#home'

   # login_path
   get '/login' => 'sessions#new'

   # create_path
   post '/login' => 'sessions#login'

   # logout_path
   get '/logout' => 'sessions#logout'
   get '/auth/:provider/callback' => 'sessions#login'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :team
  belongs_to :player

  #validates :name , presence: true
  scope :ordered_by_name, -> { order(name: :asc) }

end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
	before_action :require_login, :authenticate_user
	before_action :set_team, only: [:edit, :update, :show, :index, :create, :new]
	before_action :set_assignment, only: [:show, :edit, :update]

	skip_before_action :verify_authenticity_token

	def index
		if params[:team_id]
			#1st you retrieve the team thanks to params[:team_id]
			team = Team.find(params[:team_id])
			#2nd you get all the assignments of this post
			@assignments = team.assignments
		else
			@assignments = Assignment.all
		end
	end

	def new
			@assignment = Assignment.new(team_id: params[:team_id])
	end

	def create
		@team = Team.find(params["assignment"]["team_id"])
		@assignment = @team.assignments.build(assignment_params)
			if @assignment.save
				respond_to do |format|
					format.json { render json: @assignment.to_json }
					format.html { render :show }
				end
			else
			redirect_to new_assignment_path, alert: "Error: #{@assignment.errors.full_messages.join(", ")}"
		end
	end

	def show
		if @assignment
			team = Team.find(params[:team_id])
			@assignment = team.assignments.find(params[:id])
				respond_to do |format|
					format.json { render json: @assignment }
					format.html { render :show }
				end
			else
					redirect_to new_assignment_path, notice: "That team does not currently have an assignment, create one here."
			end
	end

	def edit
	end

	def update
			if @assignment.update(assignment_params)
					redirect_to team_assignment_path(params[:assignment][:team_id])
			else
					redirect_to edit_team_assignment_path(@assignment), alert: "Error: #{@assignment.errors.full_messages.join(", ")}"
			end
	end

	def destroy
			Assignment.find_by(:id => params[:id]).destroy
			flash[:notice] = "Assignment deleted."
			redirect_to assignments_path
	end

	private
		def assignment_params
			params.require(:assignment).permit(:name, :description, :player_id, :team_id)
		end

		def set_assignment
				@assignment = Assignment.find_by(:team_id => params[:team_id], :id => params[:id])
		end

		def set_team
				@team = Team.find_by(id: params[:team_id])
		end
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/views/assignments/_assignment.html.erb
<ol>
  <% @assignment.each do |assignments| %>
    <li class="assignment"><%= assignments.name %></li>
  <% end %>
</ol>

app/views/assignments/_form.html.erb
<%= form_for([@team, @assignment]) do |f| %>
<div class="center">
    <strong><%= f.label :name %></strong>
    <%= f.text_field :name %><br>

    <strong><%= f.label :description %></strong>
    <%= f.text_field :description %><br></br>

    <strong><%= f.label :team_id %></strong><br>
    <!-- <%= f.collection_check_boxes :team_id, Team.all, :id, :name %><br></br> -->
    <%= f.select(:team_id) do %>
        <%= options_from_collection_for_select(Team.all, :id, :name, :selected => @assignment.team_id) %>
    <% end %>

    <br></br>
    <strong><%= f.label :player_id %></strong><br>
    <!--<%= f.collection_check_boxes :player_id, Player.all, :id, :name %><br> -->
    <%= f.select(:player_id) do %>
        <%= options_from_collection_for_select(Player.all, :id, :name, :selected => @assignment.player_id) %>
    <% end %>

    <br></br>
    <!-- <%= f.submit %> -->
    <button type="submit" id="add_assignment" name="commit" value="Create Assignment class="btn btn-primary"">Create Assignment</button>
</div>
<% end %>

app/views/assignments/edit.html.erb
<h1>Edit this assignment</h1>

<%= render 'form' %>

app/views/assignments/index.html.erb
<h1>Assignments</h1>
<ul id="assignmentList align">
<% @assignments.each do |a| %>
    <li>
      <%= a.player.name %> is assigned to the <%= a.team.name %>. <p class="name_desc">Name: <%= a.name %>,<br /> Description: <%= a.description %></p>
    </li>
<% end %>
</ul>
<br>


<li><a href="/home"><button class="btn btn-primary">Home</button></a></li>

app/views/assignments/new.html.erb
<h1>New assignment</h1>

<%= render 'form' %>

app/views/assignments/show.html.erb
<h2>Assignment Information</h2>

Assignment Name, Number: <%= @assignment.name %>, #<%= @assignment.id %><br>
Assignment Description: <%= @assignment.description %><br>
Assigned Team: #<%= @assignment.team_id %> - <%= @assignment.team.name %><br>
Assigned Player: #<%= @assignment.player_id %> - <%= @assignment.player.name %><br>
<br></br>
<p><%= link_to "Edit this assignment", edit_assignment_path(@assignment.id) %></p>
<p><%= link_to "Delete", @assignment, method: :delete, data: { confirm: "Confirm Deleting?" } %></p>