config/routes.rb
Rails.application.routes.draw do

  resources :players

  resources :teams do
    resources :assignments
  end

  resources :assignments

   get '/leader' => 'players#leaders'

  root 'sessions#welcome'

  # home_path
   get '/home' => 'sessions#home'

   # login_path
   get '/login' => 'sessions#new'

   # create_path
   post '/login' => 'sessions#login'

   # logout_path
   get '/logout' => 'sessions#logout'
   get '/auth/:provider/callback' => 'sessions#login'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/player.rb
class Player < ApplicationRecord
  has_secure_password

  has_many :assignments
  has_many :teams, through: :assignments

  validates_presence_of :name
  validates :name, uniqueness: { scope: :specialty, message: "A player with that specialty already exists" }
  validates :name, uniqueness: true

  scope :leader, -> { where(leader: true) }

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
    before_action :require_login, except: [:new, :create]

    def index
        @players = Player.all
        render json: @players
    end

    def leaders
      @players = Player.leader
    end

      def new
          @player = Player.new
      end

      def create
          @player = Player.new(player_params)
          if @player.save
              session[:player_id] = @player.id
              redirect_to player_path(@player), notice: "Player sign up was successful."
          else
              redirect_to new_player_path, notice: "Uh-oh there was and error."
          end
      end

      def show
          @player = Player.find_by(id: params[:id])
          render json: @player
      end

      def edit
          if current_user.leader == true
              # Admins can edit anyone's profile
              @player = Player.find_by(id: params[:id])
          else
              # Everyone else can only edit their own
              @player = Player.find_by(id: current_user.id)
              render :edit
          end
      end

      def update
          if current_user.leader == true
              @player = Player.find_by(id: params[:id])
        else
            @player = current_user
        end

        @player.update(player_params)
        if @player.save
            redirect_to player_path(@player)
        else
            redirect_to edit_player_path(@player), error: "Error: #{@player.errors.full_messages.join(", ")}"
        end
    end

    def destroy
        if current_user.leader == true   # only admins can delete players
            if Player.find_by(:id => params[:id]) == current_user
                Player.find_by(:id => params[:id]).destroy
                session.clear   # if admin deletes themself, they get logged out
                redirect_to '/'
            elsif Player.find_by(:id => params[:id]).destroy
                Player.find_by(:id => params[:id]).destroy
                flash[:notice] = "Player record deleted."
                redirect_to players_path
            else
                  redirect_to player_path, error: "This action requires leadership"
            end
        end
    end

    private

    def player_params
        params.require(:player).permit(:name, :specialty, :leader, :password, :password_confirmation, :team_ids => [])
    end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= form_for @player do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <br>
    <%= f.label :specialty %>
    <%= f.text_field :specialty %>
    <br>
    <%= f.label :leader, "Leader?" %>
    <br>
    <%= f.radio_button :leader, "false" %>
    <%= f.label :leader_false, "No" %>
    <br>
    <%= f.radio_button :leader, "true" %>
    <%= f.label :leader_true, "Yes" %>
    <br>
    <br>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <br>
    <%= f.submit %>
<% end %>
<li><a href="/home"><button class="btn btn-primary">Home</button></a></li>

app/views/players/edit.html.erb
<h1>Edit Player Info</h1>

<%= render partial: 'form', locals: {player: @player} %>

app/views/players/index.html.erb
<h1>Current Player List:</h1>
<ul class="content align">
<% @players.each do |p| %>
    <li><%= "#{p.specialty}, #{p.name}" %> <%= link_to "Profile", player_path(p) %></li>
<% end %>
<%= link_to "Leaders", leader_path %>
</ul>
<li><a href="/home"><button class="btn btn-primary">Home</button></a></li>

app/views/players/leaders.html.erb
<h1>Leaders</h1>

<% @players.each do |p| %>
    <li><%= "#{p.specialty}, #{p.name}" %> <%= link_to "Profile", player_path(p) %></li>
<% end %>
<li><%= link_to "Players", players_path %></li>

app/views/players/new.html.erb
<h1>Welcome to the team, new player!</h1>

<%= render 'form' %>

<br></br>
<p>Already a user? <%= link_to "Log In", login_path %></p>

app/views/players/show.html.erb
<h1>Personnel file: <%= "#{@player.name}" %></h1>

<div>
    <ul>
        <li>Admin: <%= @player.leader %></li>
        <li>Specialty: <%= @player.specialty %></li>
        <br>
    </ul>
<br>
<br>
<li>Current assignment(s):<br /><br />
    <% if @player.assignments %>
        <% @player.assignments.each do |a| %>
            <%=  a.name %><br />
        <% end %>
    <% end %></li>
<div class="realign1">
<p class="realign"><%= link_to "Edit", edit_player_path(@player) %> | <%= link_to "Delete", @player, method: :delete, data: { confirm: "Confirm Deleting?" } %></p>
<li><a href="/home"><button class="btn btn-primary">Home</button></a></li>
</div>