config/routes.rb
Rails.application.routes.draw do

  resources :players

  resources :teams do
    resources :assignments
  end

  resources :assignments

   get '/leader' => 'players#leaders'

  root 'sessions#welcome'

  # home_path
   get '/home' => 'sessions#home'

   # login_path
   get '/login' => 'sessions#new'

   # create_path
   post '/login' => 'sessions#login'

   # logout_path
   get '/logout' => 'sessions#logout'
   get '/auth/:provider/callback' => 'sessions#login'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_notifications.html.erb
<div class="contain">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: [alert, alert_for(name)] %>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Team Up</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="body">
    <nav class="navbar navbar-default">
		<div class="container">
			<div class="navbar-header">
				<%= link_to "Team Up", root_path, class: "navbar-brand" %>
			</div>
			<ul class="navbar-nav nav">
				<li><%= link_to "Sign Up", new_player_path %></li>
				<% if logged_in? %>
					<li><%= link_to "Sign Out", logout_path %></li>
				<% else %>
					<li><%= link_to "Log In", login_path %></li>
				<% end %>
			</ul>
		</div>
	</nav>

    <div class="wrapper">
         <%= content_tag(:div, flash[:error], :id => "flash_error") if flash[:error] %>
         <%= content_tag(:div, flash[:notice], :id => "flash_notice") if flash[:notice] %>
         <%= content_tag(:div, flash[:alert], :id => "flash_alert") if flash[:alert] %>
         <div class="center">
           <%= yield %>
        </div
      </div>
    <script>
      $(document).ready(function(){
        setTimeout(function(){
          $('#flash_notice').fadeOut("slow", function(){
            $(this).remove();
          })
        }, 4500);
        $('#flash_notice').hide();
	       $('#flash_notice').fadeIn("slow",function(){
         });
      });
    </script>
  </body>
</html>